CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	lastname text NOT NULL CHECK (lastname <> ''),
	email text NOT NULL UNIQUE CHECK (email <> ''),
	password text NOT NULL CHECK (password <> ''));

CREATE TABLE IF NOT EXISTS tasks(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	title text NOT NULL CHECK (title <> ''),
	description text NOT NULL CHECK (description <> ''),
	deadline TIMESTAMP NOT NULL,
	completed BOOLEAN,
	delivery TIMESTAMP,
	usersId INTEGER REFERENCES users(id));

INSERT INTO public.users(
	name, lastname, email, password)
	VALUES ('fenix', '0499', 'fen1x@dmt.com', '12345');

INSERT INTO public.tasks(
	title, description, deadline, completed, usersid)
	VALUES ('Create API', 'Express.js', '2021-09-15', false, 1);

set timezone = 'Mexico/General';

select now()

--Database DLL

create table tasks
(
    id          integer generated by default as identity
        constraint tasks_pkey
            primary key,
    title       text      not null
        constraint tasks_title_check
            check (title <> ''::text),
    description text      not null
        constraint tasks_description_check
            check (description <> ''::text),
    deadline    timestamp not null,
    completed   boolean,
    "userId"    integer
        constraint tasks_usersid_fkey
            references users,
    delivery    timestamp
);

alter table tasks
    owner to postgres;

-- auto-generated definition
create table users
(
    id       integer generated by default as identity
        constraint users_pkey
            primary key,
    name     text not null
        constraint users_name_check
            check (name <> ''::text),
    lastname text not null
        constraint users_lastname_check
            check (lastname <> ''::text),
    email    text not null
        constraint users_email_key
            unique
        constraint users_email_check
            check (email <> ''::text),
    password text not null
        constraint users_password_check
            check (password <> ''::text)
);

alter table users
    owner to postgres;